spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/SecurityDB
    username : postgres
    password: 092000The
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true
